import { Brain, Cpu, Code, Zap, BarChart, Share2, Bot, Smartphone, Search, Globe, Palette } from 'lucide-react';

export const servicesData = (t: (key: string) => string) => [
  {
    id: 'ai-consulting',
    icon: Brain,
    title: t('aiConsulting'),
    description: t('aiConsultingDesc'),
    gradient: 'from-blue-500 to-blue-600',
    image: '/software.png',
  },
  {
    id: 'quantum-computing',
    icon: Cpu,
    title: t('quantumComputing'),
    description: t('quantumComputingDesc'),
    gradient: 'from-blue-400 to-blue-500',
    image: '/quntum.png',
  },
  {
    id: 'software-development',
    icon: Code,
    title: t('softwareDev'),
    description: t('softwareDevDesc'),
    gradient: 'from-blue-600 to-blue-700',
    image: '/software.png',
  },
  {
    id: 'automation',
    icon: Zap,
    title: t('automation'),
    description: t('automationDesc'),
    gradient: 'from-blue-300 to-blue-400',
    image: '/automation.png',
  },
  {
    id: 'data-marketing',
    icon: BarChart,
    title: t('dataMarketing'),
    description: t('dataMarketingDesc'),
    gradient: 'from-blue-500 to-blue-600',
    image: '/marketing.png',
  },
  {
    id: 'social-media',
    icon: Share2,
    title: t('socialMedia'),
    description: t('socialMediaDesc'),
    gradient: 'from-blue-400 to-blue-500',
    image: '/marketing.png',
  },
  {
    id: 'machine-learning',
    icon: Bot,
    title: t('machineLearning'),
    description: t('machineLearningDesc'),
    gradient: 'from-blue-600 to-blue-700',
    image: '/software.png',
  },
  {
    id: 'mobile-development',
    icon: Smartphone,
    title: t('mobileDev'),
    description: t('mobileDevDesc'),
    gradient: 'from-blue-300 to-blue-400',
    image: '/mobiel.png',
  },
  {
    id: 'seo',
    icon: Search,
    title: t('seo'),
    description: t('seoDesc'),
    gradient: 'from-blue-500 to-blue-600',
    image: '/marketing.png',
  },
  {
    id: 'web-development',
    icon: Globe,
    title: t('webDev'),
    description: t('webDevDesc'),
    gradient: 'from-blue-400 to-blue-500',
    image: '/software.png',
  },
  {
    id: 'design-content',
    icon: Palette,
    title: t('designContent'),
    description: t('designContentDesc'),
    gradient: 'from-blue-500 to-blue-600',
    image: '/design.png',
  },
]; 