import React, { createContext, useContext, useState, ReactNode } from 'react';

// English translations only
const translations = {
  // Navigation
  home: 'Home',
  services: 'Services',
  portfolio: 'Portfolio',
  about: 'About',
  contact: 'Contact',
  blog: 'Blog',
  
  // Hero
  heroTitle: 'Shaping Tomorrow with',
  heroSubtitle: 'Advanced Technology',
  heroDescription: 'Pioneering AI consulting, quantum computing, and software development to empower the digital future.',
  getStarted: 'Get Started',
  learnMore: 'Learn More',
  heroButtonText: 'Let\'s Build Your Project Together!',
  heroBadge: 'AI & Tech Specialists',
  heroTechWords: 'AI Solutions,Quantum Computing,Automation,Innovation',
  heroScrollDown: 'Scroll Down',
  heroTechAI: 'AI',
  heroTechAIDesc: 'Artificial Intelligence',
  heroTechQC: 'QC',
  heroTechQCDesc: 'Quantum Computing',
  heroTechML: 'ML',
  heroTechMLDesc: 'Machine Learning',
  heroTechAUTO: 'AUTO',
  heroTechAUTODesc: 'Automation',
  
  // Portfolio Categories
  all: 'All',
  ai: 'AI',
  machineLearning: 'Machine Learning',
  automation: 'Automation',
  mobileApp: 'Mobile App',
  quantumComputing: 'Quantum Computing',
  softwareDevelopment: 'Software Development',
  ecommerce: 'E-commerce',
  seo: 'SEO',
  socialMedia: 'Social Media',
  design: 'Design',
  
  // Portfolio Status
  live: 'Live',
  comingSoon: 'Coming Soon',
  inDevelopment: 'In Development',
  featured: 'Featured',
  
  // Portfolio Actions
  readMore: 'Read More',
  viewLive: 'View Live',
  viewCode: 'View Code',
  noProjectsFound: 'No Projects Found',
  noProjectsFoundDesc: 'No projects found for the selected category.',
  viewAllProjects: 'View All Projects',
  
  // Portfolio
  portfolioTitle: 'Innovation in Action',
  portfolioDescription: 'Explore our cutting-edge projects that showcase the power of AI, quantum computing, and advanced automation technologies.',
  portfolioCTA: 'Let\'s collaborate to bring your innovative ideas to life with cutting-edge technology solutions.',
  
  // Project Details
  projectChallenges: 'Challenges',
  projectSolutions: 'Solutions',
  projectResults: 'Results & Impact',
  projectTechnologies: 'Technologies Used',
  projectTimeline: 'Timeline',
  projectTeam: 'Team Size',
  projectStatus: 'Status',
  backToPortfolio: 'Back to Portfolio',
  viewLiveProject: 'View Live Project',
  readyToStart: 'Ready to Start Your Project?',
  startYourProject: 'Start Your Project',
  
  // Portfolio Projects - Vettek
  vettekTitle: 'Vettek - AI Hiring Platform',
  vettekDesc: 'In-house developed AI-powered recruitment platform that automates the entire hiring process from CV parsing to intelligent interviews, revolutionizing talent acquisition.',
  vettekLongDesc: 'Vettek represents a breakthrough in recruitment technology, leveraging advanced AI algorithms to transform how companies discover and evaluate talent. Our platform eliminates traditional hiring biases while dramatically reducing time-to-hire through intelligent automation.',
  vettekTimeline: '6 months',
  vettekTeam: '5 developers',
  vettekChallenge1: 'Implementing accurate CV parsing across multiple formats',
  vettekChallenge2: 'Creating realistic AI interview simulations',
  vettekChallenge3: 'Ensuring bias-free candidate evaluation',
  vettekChallenge4: 'Scaling the platform for enterprise clients',
  vettekSolution1: 'Advanced NLP models for document analysis',
  vettekSolution2: 'Conversational AI with natural language processing',
  vettekSolution3: 'Ethical AI frameworks and bias detection',
  vettekSolution4: 'Cloud-native architecture with auto-scaling',
  vettekResult1: '75% reduction in screening time',
  vettekResult2: '46% more successful hires',
  vettekResult3: '90% reduction in time-to-hire',
  vettekResult4: 'Eliminated unconscious bias in initial screening',
  
  // Portfolio Projects - Festi
  festiTitle: 'Festi - Festival Dating App',
  festiDesc: 'Mobile application exclusively for festival-goers with verified tickets, enabling connections and matches between people attending the same festivals.',
  festiLongDesc: 'Festi revolutionizes festival experiences by creating meaningful connections between attendees. Our mobile platform uses ticket verification to ensure authentic festival-goer interactions, fostering a community of music and festival enthusiasts.',
  festiTimeline: '4 months',
  festiTeam: '3 developers',
  festiChallenge1: 'Implementing secure ticket verification system',
  festiChallenge2: 'Creating location-based matching algorithms',
  festiChallenge3: 'Building real-time chat functionality',
  festiChallenge4: 'Ensuring user privacy and safety',
  festiSolution1: 'Blockchain-based ticket verification',
  festiSolution2: 'GPS and beacon technology integration',
  festiSolution3: 'Real-time messaging infrastructure',
  festiSolution4: 'Advanced privacy protection protocols',
  festiResult1: '85% user engagement rate',
  festiResult2: '92% successful matches',
  festiResult3: 'Zero security incidents',
  festiResult4: '4.8/5 app store rating',
  
  // Portfolio Projects - Knaap
  knaapTitle: 'Knaap Smart Automation',
  knaapDesc: 'Intelligent automation system for Knaap that processes leasing offers automatically through smart workflow automation and API integrations.',
  knaapLongDesc: 'Knaap Smart Automation transforms the leasing process through intelligent workflow automation. Our system automatically processes leasing offers, validates applications, and streamlines the entire customer journey from inquiry to approval.',
  knaapTimeline: '3 months',
  knaapTeam: '4 developers',
  knaapChallenge1: 'Integrating with multiple leasing systems',
  knaapChallenge2: 'Automating complex decision workflows',
  knaapChallenge3: 'Ensuring data accuracy and compliance',
  knaapChallenge4: 'Scaling for high-volume processing',
  knaapSolution1: 'RESTful API integrations',
  knaapSolution2: 'Rule-based decision engines',
  knaapSolution3: 'Real-time data validation',
  knaapSolution4: 'Microservices architecture',
  knaapResult1: '70% faster processing time',
  knaapResult2: '95% accuracy in offer generation',
  knaapResult3: '50% reduction in manual work',
  knaapResult4: '99.9% system uptime',
  
  // Portfolio Projects - Berkel
  berkelTitle: 'Berkel E-commerce Platform',
  berkelDesc: 'Complete e-commerce solution for Berkel Snijmachine with SEO optimization and integrated social media campaigns for enhanced digital presence.',
  berkelLongDesc: 'Berkel E-commerce Platform delivers a comprehensive digital solution for Berkel Snijmachine, featuring advanced e-commerce functionality, SEO optimization, and integrated social media marketing campaigns to maximize online visibility and sales.',
  berkelTimeline: '5 months',
  berkelTeam: '6 developers',
  berkelChallenge1: 'Migrating from legacy systems',
  berkelChallenge2: 'Implementing advanced SEO strategies',
  berkelChallenge3: 'Integrating social media campaigns',
  berkelChallenge4: 'Optimizing for mobile commerce',
  berkelSolution1: 'Modern e-commerce platform',
  berkelSolution2: 'Technical SEO implementation',
  berkelSolution3: 'Social media API integrations',
  berkelSolution4: 'Responsive design optimization',
  berkelResult1: '200% increase in organic traffic',
  berkelResult2: '150% boost in online sales',
  berkelResult3: '85% improvement in page load speed',
  berkelResult4: '300% growth in social media engagement',
  
  // Portfolio Projects - GBICT
  gbictTitle: 'GBICT Website',
  gbictDesc: 'Custom designed and developed website for GBICT, featuring modern UI/UX design and responsive development for optimal user experience.',
  gbictLongDesc: 'GBICT Website showcases modern web design principles with a focus on user experience and accessibility. Our custom-built platform provides GBICT with a professional online presence that effectively communicates their services and values.',
  gbictTimeline: '2 months',
  gbictTeam: '3 developers',
  gbictChallenge1: 'Creating intuitive navigation structure',
  gbictChallenge2: 'Implementing accessibility standards',
  gbictChallenge3: 'Optimizing for multiple devices',
  gbictChallenge4: 'Integrating content management system',
  gbictSolution1: 'User-centered design approach',
  gbictSolution2: 'WCAG 2.1 compliance implementation',
  gbictSolution3: 'Mobile-first responsive design',
  gbictSolution4: 'Headless CMS integration',
  gbictResult1: '95% accessibility score',
  gbictResult2: '100% mobile compatibility',
  gbictResult3: '60% faster page load times',
  gbictResult4: '40% increase in user engagement',
  
  // Portfolio Projects - Berkel Agents
  berkelAgentsTitle: 'Berkel AI Sales & Customer Agents',
  berkelAgentsDesc: 'Intelligent sales and customer service agents for Berkel Snijmachine operating across multiple channels with advanced automation capabilities.',
  berkelAgentsLongDesc: 'Berkel AI Agents revolutionize customer service and sales through intelligent automation. Our AI-powered agents handle customer inquiries, provide product recommendations, and manage sales processes across multiple communication channels.',
  berkelAgentsTimeline: '4 months',
  berkelAgentsTeam: '5 developers',
  berkelAgentsChallenge1: 'Training AI models for product knowledge',
  berkelAgentsChallenge2: 'Integrating multiple communication channels',
  berkelAgentsChallenge3: 'Ensuring natural conversation flow',
  berkelAgentsChallenge4: 'Maintaining brand consistency',
  berkelAgentsSolution1: 'Custom NLP model training',
  berkelAgentsSolution2: 'Multi-channel API integration',
  berkelAgentsSolution3: 'Conversational AI framework',
  berkelAgentsSolution4: 'Brand voice training algorithms',
  berkelAgentsResult1: '80% query resolution rate',
  berkelAgentsResult2: '24/7 customer support availability',
  berkelAgentsResult3: '65% reduction in response time',
  berkelAgentsResult4: '90% customer satisfaction score',
  
  // Portfolio Projects - Quantum
  quantumTitle: 'Quantum LLM Framework',
  quantumDesc: 'Cutting-edge quantum LLM framework designed to fine-tune large language models on quantum hardware and simulators for next-generation AI capabilities.',
  quantumLongDesc: 'Quantum LLM Framework represents the future of artificial intelligence, combining quantum computing principles with large language models. Our framework enables fine-tuning of LLMs on quantum hardware, unlocking unprecedented computational capabilities.',
  quantumTimeline: '8 months',
  quantumTeam: '7 developers',
  quantumChallenge1: 'Developing quantum-classical hybrid algorithms',
  quantumChallenge2: 'Optimizing for quantum hardware constraints',
  quantumChallenge3: 'Ensuring model accuracy and reliability',
  quantumChallenge4: 'Scaling to enterprise applications',
  quantumSolution1: 'Quantum variational algorithms',
  quantumSolution2: 'Hardware-aware optimization',
  quantumSolution3: 'Robust error correction mechanisms',
  quantumSolution4: 'Distributed quantum computing',
  quantumResult1: '10x faster training on quantum hardware',
  quantumResult2: '99.9% model accuracy maintenance',
  quantumResult3: '50% reduction in computational complexity',
  quantumResult4: 'Patent-pending quantum algorithms',
  
  // Portfolio Projects - Kusor
  kusorTitle: 'Kusor AI Agent Platform',
  kusorDesc: 'Revolutionary platform that enables users to create AI agents with simple prompts, featuring 600+ integrations and access to all edge AI models.',
  kusorLongDesc: 'Kusor AI Agent Platform democratizes AI agent creation through intuitive prompt-based interfaces. Our platform provides access to 600+ integrations and edge AI models, enabling users to build sophisticated AI agents without technical expertise.',
  kusorTimeline: '6 months',
  kusorTeam: '8 developers',
  kusorChallenge1: 'Creating intuitive prompt interfaces',
  kusorChallenge2: 'Integrating 600+ third-party services',
  kusorChallenge3: 'Optimizing for edge AI model deployment',
  kusorChallenge4: 'Ensuring platform scalability',
  kusorSolution1: 'Natural language processing engines',
  kusorSolution2: 'Comprehensive API marketplace',
  kusorSolution3: 'Edge computing optimization',
  kusorSolution4: 'Microservices architecture',
  kusorResult1: '95% user satisfaction rate',
  kusorResult2: '600+ active integrations',
  kusorResult3: '10,000+ AI agents created',
  kusorResult4: '99.9% platform uptime',
  
  // Services
  servicesTitle: 'Our Services',
  servicesSubtitle: 'Comprehensive technology solutions for your business',
  
  // Service Detail Page Content
  backToServices: 'Back to Services',
  getInTouch: 'Get In Touch',
  
  // AI Consulting Detail
  aiConsultingTitle: 'AI Consulting Services',
  aiConsultingIntro: 'Transform your business with strategic AI implementation. Our expert team provides comprehensive AI consulting to help you leverage artificial intelligence for competitive advantage.',
  aiSolutionsTitle: 'Our AI Solutions',
  aiSolution1: 'Machine Learning Model Development',
  aiSolution2: 'Natural Language Processing Systems',
  aiSolution3: 'Computer Vision Applications',
  aiSolution4: 'Predictive Analytics Solutions',
  aiSolution5: 'AI Strategy & Roadmap Planning',
  aiSolution6: 'AI Integration & Implementation',
  aiSolution7: 'AI Training & Support',
  whyChooseAiTitle: 'Why Choose Our AI Consulting',
  aiExpertTeam: 'Expert AI Team',
  aiExpertTeamDesc: 'Certified AI professionals with deep industry experience',
  aiPracticalApproach: 'Practical Approach',
  aiPracticalApproachDesc: 'Focus on real-world applications and measurable results',
  aiEndToEndSupport: 'End-to-End Support',
  aiEndToEndSupportDesc: 'From strategy to implementation and maintenance',
  aiIndustryExpertise: 'Industry Expertise',
  aiIndustryExpertiseDesc: 'Specialized knowledge across multiple sectors',
  aiClosing: 'Ready to unlock the power of AI for your business? Contact us for a free consultation and discover how artificial intelligence can transform your operations.',
  
  // Web Development Detail
  webTitle: 'Website Development',
  webIntro: 'Modern, responsive websites built for performance. We create stunning web experiences that drive results and engage your audience.',
  webServicesTitle: 'Web Development Services',
  webService1: 'Custom Website Design',
  webService2: 'E-commerce Development',
  webService3: 'Progressive Web Apps (PWA)',
  webService4: 'API Development & Integration',
  webService5: 'Database Design & Optimization',
  webService6: 'Cloud Hosting & Deployment',
  webService7: 'Performance Optimization',
  webService8: 'Maintenance & Support',
  webTechnologiesTitle: 'Technologies We Use',
  react: 'React',
  reactDesc: 'Modern JavaScript library for building interactive user interfaces',
  nodejs: 'Node.js',
  nodejsDesc: 'Server-side JavaScript runtime for scalable backend development',
  nextjs: 'Next.js',
  nextjsDesc: 'React framework for production-ready applications with SSR',
  typescript: 'TypeScript',
  typescriptDesc: 'Type-safe JavaScript for robust and maintainable code',
  webClosing: 'Ready to build your next web project? Contact us for a free consultation and let\'s create something amazing together.',
  
  // Machine Learning Detail
  mlTitle: 'Machine Learning Solutions',
  mlIntro: 'Unlock insights from your data with advanced machine learning algorithms. Our ML solutions help you make data-driven decisions and automate complex processes.',
  mlServicesTitle: 'ML Services',
  mlService1: 'Predictive Modeling',
  mlService2: 'Classification Systems',
  mlService3: 'Recommendation Engines',
  mlService4: 'Anomaly Detection',
  mlService5: 'Natural Language Processing',
  mlService6: 'Computer Vision',
  mlService7: 'ML Model Deployment',
  mlService8: 'ML Model Optimization',
  mlIndustryTitle: 'Industry Applications',
  financialServices: 'Financial Services',
  financialServicesDesc: 'Fraud detection, risk assessment, algorithmic trading, and credit scoring',
  healthcare: 'Healthcare',
  healthcareDesc: 'Medical diagnosis, drug discovery, patient monitoring, and treatment optimization',
  retail: 'Retail',
  retailDesc: 'Demand forecasting, inventory optimization, customer segmentation, and pricing strategies',
  manufacturing: 'Manufacturing',
  manufacturingDesc: 'Predictive maintenance, quality control, supply chain optimization, and process automation',
  mlClosing: 'Transform your data into actionable insights. Contact us for machine learning solutions.',
  
  // Software Development Detail
  softwareTitle: 'Software Development',
  softwareIntro: 'Custom software solutions built to scale. We develop robust, secure, and maintainable applications that drive your business forward.',
  softwareServicesTitle: 'Software Development Services',
  softwareService1: 'Custom Application Development',
  softwareService2: 'Enterprise Software Solutions',
  softwareService3: 'API Development & Integration',
  softwareService4: 'Database Design & Management',
  softwareService5: 'Cloud-Native Applications',
  softwareService6: 'Legacy System Modernization',
  softwareService7: 'Software Testing & Quality Assurance',
  softwareProcessTitle: 'Development Process',
  softwareStep1: 'Requirements Analysis',
  softwareStep1Desc: 'Understanding your business needs and technical requirements',
  softwareStep2: 'System Design',
  softwareStep2Desc: 'Creating scalable architecture and technical specifications',
  softwareStep3: 'Development & Testing',
  softwareStep3Desc: 'Building and thoroughly testing your software solution',
  softwareStep4: 'Deployment & Support',
  softwareStep4Desc: 'Launching your application and providing ongoing maintenance',
  softwareClosing: 'Ready to build your custom software solution? Contact us for a free consultation and let\'s create something amazing together.',
  
  // Quantum Computing Detail
  quantumServiceTitle: 'Quantum Computing Solutions',
  quantumIntro: 'Harness the power of quantum computing for complex problem-solving. Our quantum solutions provide exponential computational advantages for optimization, cryptography, and simulation challenges.',
  quantumServicesTitle: 'Quantum Services',
  quantumService1: 'Quantum Algorithm Development',
  quantumService2: 'Quantum Circuit Design',
  quantumService3: 'Quantum Optimization Solutions',
  quantumService4: 'Quantum Cryptography Implementation',
  quantumService5: 'Quantum Simulation Services',
  quantumService6: 'Quantum Hardware Integration',
  quantumService7: 'Quantum Computing Consulting',
  quantumApplicationsTitle: 'Quantum Applications',
  quantumOptimization: 'Optimization',
  quantumOptimizationDesc: 'Solve complex optimization problems exponentially faster',
  quantumCryptography: 'Cryptography',
  quantumCryptographyDesc: 'Unbreakable quantum encryption for secure communications',
  quantumSimulation: 'Simulation',
  quantumSimulationDesc: 'Simulate quantum systems for research and development',
  quantumClosing: 'Explore the future of computing with our quantum solutions. Contact us to discuss how quantum computing can revolutionize your industry.',
  
  // Software Development Detail
  softwareDevTitle: 'Custom Software Development',
  softwareDevIntro: 'Build powerful, scalable software solutions tailored to your business needs. Our development team creates custom applications using cutting-edge technologies and best practices.',
  softwareDevServicesTitle: 'Development Services',
  softwareDevService1: 'Web Application Development',
  softwareDevService2: 'Mobile App Development',
  softwareDevService3: 'Desktop Software Solutions',
  softwareDevService4: 'API Development & Integration',
  softwareDevService5: 'Database Design & Optimization',
  softwareDevService6: 'Cloud-Native Applications',
  softwareDevService7: 'Legacy System Modernization',
  softwareDevTechTitle: 'Technologies We Use',
  softwareDevTech1: 'Frontend: React, Vue.js, Angular',
  softwareDevTech2: 'Backend: Node.js, Python, Java',
  softwareDevTech3: 'Mobile: React Native, Flutter',
  softwareDevTech4: 'Cloud: AWS, Azure, Google Cloud',
  softwareDevClosing: 'Transform your ideas into powerful software solutions. Contact us to discuss your development project.',
  
  // Automation Detail
  automationTitle: 'Automation Solutions',
  automationIntro: 'Streamline your business processes with intelligent automation. We help you eliminate repetitive tasks, reduce errors, and increase efficiency through smart automation solutions.',
  automationServicesTitle: 'Automation Services',
  automationService1: 'Business Process Automation',
  automationService2: 'Workflow Automation',
  automationService3: 'Data Processing Automation',
  automationService4: 'Email & Communication Automation',
  automationService5: 'Document Processing Automation',
  automationService6: 'Customer Service Automation',
  automationService7: 'Inventory Management Automation',
  automationBenefitsTitle: 'Automation Benefits',
  automationBenefit1: 'Increased Efficiency',
  automationBenefit1Desc: 'Reduce manual work and speed up processes',
  automationBenefit2: 'Cost Reduction',
  automationBenefit2Desc: 'Lower operational costs through automation',
  automationBenefit3: 'Error Reduction',
  automationBenefit3Desc: 'Minimize human errors and improve accuracy',
  automationBenefit4: '24/7 Operations',
  automationBenefit4Desc: 'Automated processes run around the clock',
  automationClosing: 'Ready to automate your business processes? Contact us for a free consultation and discover how automation can transform your operations.',
  automationSolutionsTitle: 'Automation Solutions',
  automationSolution1: 'Business Process Automation',
  automationSolution2: 'Workflow Automation',
  automationSolution3: 'Data Processing Automation',
  automationSolution4: 'Email & Communication Automation',
  automationSolution5: 'Document Processing Automation',
  automationSolution6: 'Customer Service Automation',
  automationSolution7: 'Inventory Management Automation',
  automationSolution8: 'Financial Process Automation',
  
  // Mobile Development Detail
  mobileTitle: 'Mobile App Development',
  mobileIntro: 'Create powerful, user-friendly mobile applications for iOS and Android. Our mobile development team delivers native and cross-platform solutions that engage users and drive business growth.',
  mobileServicesTitle: 'Mobile Development Services',
  mobileService1: 'Native iOS Development',
  mobileService2: 'Native Android Development',
  mobileService3: 'Cross-Platform Development',
  mobileService4: 'Mobile App Design',
  mobileService5: 'App Store Optimization',
  mobileService6: 'Mobile App Testing',
  mobileService7: 'App Maintenance & Updates',
  mobileService8: 'Mobile Analytics Integration',
  mobileProcessTitle: 'Development Process',
  mobileStep1: 'Planning & Strategy',
  mobileStep1Desc: 'Define app requirements, target audience, and technical specifications',
  mobileStep2: 'Design & Prototyping',
  mobileStep2Desc: 'Create user interface designs and interactive prototypes',
  mobileStep3: 'Development & Testing',
  mobileStep3Desc: 'Build the app with rigorous testing and quality assurance',
  mobileStep4: 'Launch & Optimization',
  mobileStep4Desc: 'Deploy to app stores and continuously optimize performance',
  mobileClosing: 'Transform your ideas into mobile success. Contact us for mobile app development services.',
  
  // Design & Content Creation Detail
  designTitle: 'Design & Content Creation',
  designIntro: 'Create compelling visual designs and engaging content that captivates your audience. Our design team delivers stunning visuals and strategic content that drives engagement and conversions.',
  designServicesTitle: 'Design Services',
  designService1: 'Brand Identity Design',
  designService2: 'Logo Design & Branding',
  designService3: 'Web Design & UI/UX',
  designService4: 'Print Design',
  designService5: 'Social Media Graphics',
  designService6: 'Content Writing',
  designService7: 'Video Production',
  designService8: 'Photography & Visual Assets',
  designProcessTitle: 'Design Process',
  designStep1: 'Discovery & Research',
  designStep1Desc: 'Understand your brand, audience, and design requirements',
  designStep2: 'Concept & Strategy',
  designStep2Desc: 'Develop design concepts and creative strategies',
  designStep3: 'Design & Creation',
  designStep3Desc: 'Create visual designs and content assets',
  designStep4: 'Review & Refinement',
  designStep4Desc: 'Refine designs based on feedback and finalize deliverables',
  designClosing: 'Bring your brand to life with stunning design. Contact us for design and content creation services.',
  
  // Data Marketing Detail
  dataMarketingTitle: 'Data-Driven Marketing Solutions',
  dataMarketingIntro: 'Leverage data insights to create targeted, effective marketing campaigns. Our data marketing solutions help you reach the right audience with the right message at the right time.',
  dataMarketingServicesTitle: 'Marketing Services',
  dataMarketingService1: 'Customer Analytics & Segmentation',
  dataMarketingService2: 'Predictive Marketing Models',
  dataMarketingService3: 'Campaign Performance Analysis',
  dataMarketingService4: 'Marketing Automation Setup',
  dataMarketingService5: 'A/B Testing & Optimization',
  dataMarketingService6: 'ROI Tracking & Reporting',
  dataMarketingService7: 'Personalization Strategies',
  dataMarketingClosing: 'Drive better marketing results with data. Contact us to optimize your marketing strategy.',
  dataMarketingChannelsTitle: 'Digital Marketing Channels',
  digitalChannels: 'Digital Channels',
  digitalChannel1: 'Social Media Marketing',
  digitalChannel2: 'Search Engine Marketing (SEM)',
  digitalChannel3: 'Email Marketing Campaigns',
  digitalChannel4: 'Content Marketing',
  digitalChannel5: 'Display Advertising',
  analyticsInsights: 'Analytics & Insights',
  analyticsInsight1: 'Campaign Performance Tracking',
  analyticsInsight2: 'Customer Behavior Analysis',
  analyticsInsight3: 'ROI Measurement & Optimization',
  analyticsInsight4: 'A/B Testing & Conversion Optimization',
  analyticsInsight5: 'Predictive Analytics for Marketing',
  
  // Social Media Detail
  socialMediaTitle: 'Social Media Management',
  socialMediaIntro: 'Build and maintain a strong social media presence across all platforms. Our comprehensive social media management helps you engage with your audience and grow your brand.',
  socialMediaServicesTitle: 'Social Media Services',
  socialMediaService1: 'Content Strategy & Creation',
  socialMediaService2: 'Community Management',
  socialMediaService3: 'Social Media Advertising',
  socialMediaService4: 'Influencer Partnerships',
  socialMediaService5: 'Analytics & Reporting',
  socialMediaService6: 'Crisis Management',
  socialMediaService7: 'Platform Optimization',
  socialMediaService8: 'Social Media Strategy',
  socialMediaPlatformsTitle: 'Social Media Platforms',
  facebook: 'Facebook',
  facebookDesc: 'Community building and brand awareness',
  instagram: 'Instagram',
  instagramDesc: 'Visual storytelling and engagement',
  linkedin: 'LinkedIn',
  linkedinDesc: 'Professional networking and B2B',
  youtube: 'YouTube',
  youtubeDesc: 'Video content and tutorials',
  socialMediaClosing: 'Grow your social media presence. Contact us to elevate your social media strategy.',
  
  // Machine Learning Detail
  machineLearningTitle: 'Machine Learning Solutions',
  machineLearningIntro: 'Unlock insights from your data with advanced machine learning algorithms. Our ML solutions help you make data-driven decisions and automate complex processes.',
  machineLearningServicesTitle: 'ML Services',
  machineLearningService1: 'Predictive Modeling',
  machineLearningService2: 'Classification Systems',
  machineLearningService3: 'Recommendation Engines',
  machineLearningService4: 'Anomaly Detection',
  machineLearningService5: 'Natural Language Processing',
  machineLearningService6: 'Computer Vision',
  machineLearningService7: 'ML Model Deployment',
  machineLearningClosing: 'Transform your data into actionable insights. Contact us for machine learning solutions.',
  
  // Mobile Development Detail
  mobileDevTitle: 'Mobile App Development',
  mobileDevIntro: 'Create powerful mobile applications for iOS and Android. Our mobile development team builds native and cross-platform apps that deliver exceptional user experiences.',
  mobileDevServicesTitle: 'Mobile Services',
  mobileDevService1: 'Native iOS Development',
  mobileDevService2: 'Native Android Development',
  mobileDevService3: 'Cross-Platform Development',
  mobileDevService4: 'Mobile App Design',
  mobileDevService5: 'App Store Optimization',
  mobileDevService6: 'Mobile App Testing',
  mobileDevService7: 'App Maintenance & Updates',
  mobileDevClosing: 'Bring your app idea to life. Contact us for mobile development services.',
  
  // SEO Detail
  seoTitle: 'SEO Optimization Services',
  seoIntro: 'Improve your online visibility and drive organic traffic with our comprehensive SEO services. Our SEO experts help you rank higher in search results and attract more qualified leads.',
  seoServicesTitle: 'SEO Services',
  seoService1: 'Technical SEO Audit',
  seoService2: 'Keyword Research & Strategy',
  seoService3: 'On-Page Optimization',
  seoService4: 'Content Optimization',
  seoService5: 'Link Building',
  seoService6: 'Local SEO',
  seoService7: 'SEO Performance Tracking',
  seoService8: 'Technical SEO Optimization',
  seoResultsTitle: 'SEO Results',
  seoResult1: 'Higher Rankings',
  seoResult1Desc: 'Improved search engine visibility',
  seoResult2: 'More Traffic',
  seoResult2Desc: 'Increased organic website traffic',
  seoResult3: 'Better Conversions',
  seoResult3Desc: 'Higher quality leads and sales',
  seoClosing: 'Boost your search rankings. Contact us for SEO optimization services.',
  
  // Web Development Detail
  webDevTitle: 'Website Development',
  webDevIntro: 'Build modern, responsive websites that deliver exceptional user experiences. Our web development team creates fast, secure, and scalable websites tailored to your business needs.',
  webDevServicesTitle: 'Web Development Services',
  webDevService1: 'Responsive Web Design',
  webDevService2: 'E-commerce Development',
  webDevService3: 'Content Management Systems',
  webDevService4: 'Custom Web Applications',
  webDevService5: 'Website Performance Optimization',
  webDevService6: 'Security Implementation',
  webDevService7: 'Website Maintenance',
  webDevClosing: 'Create a powerful web presence. Contact us for website development services.',
  
  // Design & Content Detail
  designContentTitle: 'Design & Content Creation',
  designContentIntro: 'Create compelling visual designs and engaging content that captures your brand essence. Our design and content team helps you communicate effectively with your audience.',
  designContentServicesTitle: 'Design & Content Services',
  designContentService1: 'Brand Identity Design',
  designContentService2: 'Graphic Design',
  designContentService3: 'Content Writing',
  designContentService4: 'Video Production',
  designContentService5: 'Photography',
  designContentService6: 'UI/UX Design',
  designContentService7: 'Marketing Materials',
  designContentClosing: 'Bring your brand to life. Contact us for design and content services.',
  
  // About
  aboutTitle: 'About Bright-Byte',
  aboutDescription: 'We are AI & Tech Specialists - hands-on builders with deep domain knowledge. Our cutting-edge technology company specializes in AI, quantum computing, and comprehensive digital solutions, delivering innovative solutions that drive business transformation.',
  aiTechSpecialists: 'AI Tech Specialists',
  successfulProjects: 'Successful Projects',
  technicalSupport: 'Technical Support',
  clientSatisfaction: 'Client Satisfaction',
  yearsOfExcellence: 'Years of Excellence',
  pioneeringFuture: 'Pioneering the Future of Technology',
  
  // Contact
  contactTitle: 'Get In Touch',
  contactDescription: 'Ready to transform your business with cutting-edge technology?',
  contactUs: 'Contact Us',
  
  // Contact Page
  sendMessageTitle: 'Send us a Message',
  contactInfoTitle: 'Contact Information',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  subject: 'Subject',
  message: 'Message',
  sendMessage: 'Send Message',
  sending: 'Sending...',
  messageSent: 'Message sent successfully! We will get back to you soon.',
  
  // Form placeholders
  firstNamePlaceholder: 'John',
  lastNamePlaceholder: 'Doe',
  emailPlaceholder: 'john@example.com',
  subjectPlaceholder: 'How can we help?',
  messagePlaceholder: 'Tell us about your project...',
  
  // Contact Info Headers
  emailTitle: 'Email',
  phoneTitle: 'Phone',
  locationTitle: 'Location',
  
  // Quick Response Guarantee
  quickResponseTitle: 'Quick Response Guarantee',
  quickResponseDescription: 'We pride ourselves on quick communication. You\'ll receive an automatic confirmation email immediately, and our team will personally respond to your inquiry within 24 hours.',
  
  // Footer
  footerDescription: 'Innovative technology solutions transforming businesses with advanced AI, quantum computing, and digital solutions.',
  footerServicesTitle: 'Services',
  footerContactTitle: 'Contact',
  footerLocationTitle: 'Location',
  footerCopyright: '2025 Bright-Byte. All rights reserved.',
  privacyPolicy: 'Privacy Policy',
  
  // Success Modal and Toast Messages
  thankYouMessage: 'Thank you',
  successModalMessage: 'Your message has been successfully sent to our team. We appreciate your interest in Bright-Byte and will get back to you within',
  hoursResponse: '24 hours',
  confirmationEmailSent: 'Confirmation email sent to your inbox',
  continueExploring: 'Continue Exploring',
  callUs: 'Call us:',
  
  // Toast Error Messages
  emailServiceNotConfigured: 'Email service not configured yet. Please set up EmailJS credentials.',
  emailError: 'Email Error:',
  contactFormIssue: 'There was an issue with our contact form. Your email client has been opened as a backup. We apologize for the inconvenience.',
  
  // Additional Success Messages
  messageSuccessfullySent: 'Your message has been successfully sent to our team',
  appreciateInterest: 'We appreciate your interest in Bright-Byte',
  responseWithin: 'and will get back to you within',
  confirmationEmail: 'Confirmation email sent to your inbox',
  
  // About Page
  aboutPageTitle: 'About Bright-Byte',
  aboutPageSubtitle: 'Pioneering the Future of Technology',
  ourStoryTitle: 'Our Story',
  ourStoryParagraph1: 'Founded with a vision to bridge the gap between cutting-edge technology and real-world applications, Bright-Byte has emerged as a leading force in AI consulting, quantum computing, and software development.',
  ourStoryParagraph2: 'Our journey began with a simple belief: technology should empower businesses, not complicate them. Today, we\'re proud to be at the forefront of innovation, helping organizations transform their digital landscape.',
  getInTouchButton: 'Get In Touch',
  ourValuesTitle: 'Our Values',
  ourValuesSubtitle: 'The Principles That Drive Us',
  valueInnovationTitle: 'Innovation',
  valueInnovationDesc: 'We constantly push the boundaries of what\'s possible, exploring emerging technologies and creating solutions that set new industry standards.',
  valueCollaborationTitle: 'Collaboration',
  valueCollaborationDesc: 'We believe the best results come from working closely with our clients, understanding their unique challenges and co-creating tailored solutions.',
  valueExcellenceTitle: 'Excellence',
  valueExcellenceDesc: 'Every project receives our unwavering commitment to quality, attention to detail, and pursuit of perfection in both process and outcome.',
  valueCreativityTitle: 'Creativity',
  valueCreativityDesc: 'We approach complex problems with fresh perspectives, combining technical expertise with creative thinking to deliver innovative solutions.',
  ourMissionTitle: 'Our Mission',
  ourMissionDescription: 'To democratize advanced technology and make AI, quantum computing, and cutting-edge software development accessible to businesses of all sizes, empowering them to thrive in the digital age.',
  exploreServicesButton: 'Explore Our Services',
  
  // Cookie Consent
  cookieConsentTitle: 'We use cookies',
  cookieConsentDescription: 'We use cookies to enhance your browsing experience, serve personalized content, and analyze our traffic. By clicking "Accept All", you consent to our use of cookies.',
  cookieAccept: 'Accept All',
  cookieDecline: 'Decline',
  
  // Consultation
  consultationAvailable: 'Available Now',
  consultationTitle: 'Free Technology Consultation',
  consultationSubtitle: 'Get Expert Advice on Your Next Project',
  consultationDescription: 'Book a free 30-minute consultation with our technology experts to discuss your project requirements, explore solutions, and get personalized recommendations.',
  consultationBenefit1: 'Expert technology guidance',
  consultationBenefit2: 'Personalized project roadmap',
  consultationBenefit3: 'Cost and timeline estimates',
  consultationBenefit4: 'No obligation, completely free',
  consultationButton: 'Book Free Consultation',
  consultationDuration: '30 minutes',
  consultationType: 'Video Call',
  consultationCoverTitle: 'What We\'ll Cover',
  consultationCover1: 'Project requirements analysis',
  consultationCover2: 'Technology stack recommendations',
  consultationCover3: 'Development approach & timeline',
  consultationCover4: 'Budget and resource planning',
  
  // Service names (used in servicesData.ts cards)
  aiConsulting: 'AI Consulting',
  aiConsultingDesc: 'Strategic AI implementation to transform your business processes and drive innovation.',
  quantumComputingDesc: 'Next-generation quantum solutions for complex computational challenges.',
  softwareDev: 'Software Development',
  softwareDevDesc: 'Custom software solutions built with cutting-edge technologies and best practices.',
  automationDesc: 'Intelligent automation systems that streamline operations and reduce costs.',
  dataMarketing: 'Data Marketing',
  dataMarketingDesc: 'Data-driven marketing strategies that deliver measurable business results.',
  socialMediaDesc: 'Comprehensive social media management and marketing campaigns.',
  machineLearningDesc: 'Advanced ML models and algorithms for data-driven insights and automation.',
  mobileDev: 'Mobile Development',
  mobileDevDesc: 'Native and cross-platform mobile applications for iOS and Android.',
  seoDesc: 'Data-driven SEO strategies to improve visibility and organic traffic.',
  webDev: 'Web Development',
  webDevDesc: 'Modern, responsive websites built for performance and user experience.',
  designContent: 'Design & Content',
  designContentDesc: 'Compelling visual designs and engaging content that captivates your audience.',
  dataMarketingService8: 'Customer Lifetime Value Optimization',
};

interface LanguageContextType {
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const t = (key: string): string => {
    const translation = translations[key as keyof typeof translations];
    if (!translation) {
      console.warn(`Missing translation for key: "${key}"`);
      return key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
